version: "3.5"
services:
  app1: &api
    build: .
    expose:
      - "8080"
    network_mode: "host"
    restart: always
    environment:
      - PORT=8080
      - TIMEOUT=5000
    deploy:
      resources:
        limits:
           cpus: "2.5"
           memory: "500MB"
  app2:
    <<: *api
    environment:
      - PORT=8081
      - TIMEOUT=5000
  db:
    image: mongo
    network_mode: "host"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root    
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "500MB"  
  nginx:
    image: nginx
    hostname: api
    network_mode: "host"
    volumes:
      - ./scripts/nginx/:/etc/nginx/
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "150MB"

